apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sinatra-monitor
  namespace: metrics-playground
spec:
  endpoints:
  - interval: 30s
    port: 8080-tcp
    scheme: http
  selector:
    matchLabels:
      app: sinatra-app